trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Node.js
- task: UseNode@1
inputs:
    version: '16.x' # Adjust based on your Node.js version

# Install dependencies
-  script: |
    npm install
  displayName: 'Install dependencies'

# Run tests (optional, if you have tests configured)


# Build the application (optional, if your app needs building)
- script: |
    npm run build
  displayName: 'Build application'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnectionhealthbridge-app'
    appName: 'healthbridge-app'
    package: $(System.DefaultWorkingDirectory)
