name: CI/CD Pipeline for Node.js to Azure

on:
  push:
    branches:
      - main1  # Adjust if using a different default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust the version based on your project

      # # Build the application (if applicable)
      - name: AZ Login
        run: |
          npm install
      # - name: AZ Deploy
      #   run: |
      #     zip -r app.zip .
      #     az webapp deployment source config-zip --resource-group AppDeploymentRG --name healthbridge-app --src app.zip
          

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "HealthBridgeApp" # Replace with your Azure App name
          publish-profile: ${{ secrets.HEALTH_BRIDGE_SECRETS }}
